// Package api embeds the generated OpenAPI spec for Windshift's public
// REST API so the running binary can serve it without a filesystem
// dependency. The spec files themselves are regenerated by `make openapi`
// from swag annotations on the handlers; this package never edits them.
package api

import _ "embed"

// SpecJSON is the OpenAPI 3.0 spec serialized as JSON.
//
//go:embed openapi.json
var SpecJSON []byte

// SpecYAML is the OpenAPI 3.0 spec serialized as YAML.
//
//go:embed openapi.yaml
var SpecYAML []byte
